# Generated by Django 5.2.3 on 2025-07-08 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, default='', max_length=1000)),
                ('header', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100000)),
                ('date', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
