# Generated by Django 5.2.3 on 2025-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.CharField(max_length=100),
        ),
    ]
