# Generated by Django 5.2.3 on 2025-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
