# Generated by Django 5.2.3 on 2025-07-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.CharField(max_length=1000000),
        ),
    ]
