# Generated by Django 5.2.4 on 2025-07-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField()),
                ('category', models.JSONField(default=list)),
                ('product_name', models.CharField()),
                ('product_description', models.CharField()),
                ('price', models.IntegerField()),
                ('per', models.CharField()),
                ('discount', models.BooleanField(default=False)),
                ('discount_percent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='urban_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('box', models.JSONField(default=list)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
    ]
