# Generated by Django 5.2.4 on 2025-07-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_urban_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urban_user',
            old_name='username',
            new_name='user_name',
        ),
    ]
