# Generated by Django 5.2.4 on 2025-07-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_username_urban_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_produce',
            name='category',
            field=models.CharField(),
        ),
    ]
